name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    
    - name: Setup Builder
      run: |
        pip3 install --user wheel
        pip3 install --user diskimage-builder ironic-python-agent-builder
        pip3 list -v
    - name: Generate image
      run: |
        sudo ironic-python-agent-builder fedora
