name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Setup Builder
      run: |
        pip install --user diskimage-builder ironic-python-agent-builder
    - name: Generate image
      run: |
        ironic-python-agent-builder fedora
